export * from '@/pages/main.page'
export * from '@/pages/register.page'
export * from '@/pages/yourfeed.page'
export * from '@/pages/article.page'
export * from '@/pages/login.page'
export * from '@/pages/editor.page'
export * from '@/pages/profile.page'
export * from '@/pages/settings.page'